"""Mutation testing: change the source in one small way, and demand a test notices.

A green suite proves the tests pass, not that they would fail if the code were wrong.
Mutation testing measures the second thing, which is the one that matters — every
"N/N mutants caught" figure in this project's todo means a suite that actually
detects the defect it claims to guard against.

Mutants are generated by AST rewriting, one per run, and each is applied to a COPY of
the tree so the real source is never touched even if this script is killed mid-run.

A **survivor** is the finding: a mutation nothing detected, meaning either a test is
missing or the mutated line does not matter. Both are worth knowing, and the second is
worth deleting.

Usage:
    python scripts/run_mutation_testing.py --target src/nse_algo_trader/market_depth \
        --tests tests/test_depth_tape_schema_and_integrity.py --max-mutants 40
"""

from __future__ import annotations

import argparse
import ast
import random
import shutil
import subprocess
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path

COMPARISON_INVERSIONS: dict[type[ast.cmpop], type[ast.cmpop]] = {
    ast.Lt: ast.LtE,
    ast.LtE: ast.Lt,
    ast.Gt: ast.GtE,
    ast.GtE: ast.Gt,
    ast.Eq: ast.NotEq,
    ast.NotEq: ast.Eq,
}

ARITHMETIC_SWAPS: dict[type[ast.operator], type[ast.operator]] = {
    ast.Add: ast.Sub,
    ast.Sub: ast.Add,
    ast.Mult: ast.Div,
    ast.Div: ast.Mult,
}


@dataclass(frozen=True)
class Mutant:
    """One applied change, described well enough to act on if it survives."""

    file_path: Path
    line_number: int
    description: str


class _MutationApplier(ast.NodeTransformer):
    """Applies exactly the `target_index`-th eligible mutation and records it."""

    def __init__(self, target_index: int) -> None:
        self.target_index = target_index
        self.seen = 0
        self.applied: str | None = None
        self.applied_line = 0

    def _take(self, node: ast.AST, description: str) -> bool:
        matched = self.seen == self.target_index
        self.seen += 1
        if matched:
            self.applied = description
            self.applied_line = getattr(node, "lineno", 0)
        return matched

    def visit_Compare(self, node: ast.Compare) -> ast.AST:
        self.generic_visit(node)
        for index, operator in enumerate(node.ops):
            replacement = COMPARISON_INVERSIONS.get(type(operator))
            if replacement is None:
                continue
            if self._take(node, f"{type(operator).__name__} -> {replacement.__name__}"):
                node.ops[index] = replacement()
        return node

    def visit_BinOp(self, node: ast.BinOp) -> ast.AST:
        self.generic_visit(node)
        replacement = ARITHMETIC_SWAPS.get(type(node.op))
        if replacement is not None and self._take(
            node, f"{type(node.op).__name__} -> {replacement.__name__}"
        ):
            node.op = replacement()
        return node

    def visit_BoolOp(self, node: ast.BoolOp) -> ast.AST:
        self.generic_visit(node)
        flipped = ast.Or if isinstance(node.op, ast.And) else ast.And
        if self._take(node, f"{type(node.op).__name__} -> {flipped.__name__}"):
            node.op = flipped()
        return node

    def visit_UnaryOp(self, node: ast.UnaryOp) -> ast.AST:
        self.generic_visit(node)
        if isinstance(node.op, ast.Not) and self._take(node, "drop `not`"):
            return node.operand
        return node


def count_mutation_sites(source: str) -> int:
    applier = _MutationApplier(target_index=-1)
    applier.visit(ast.parse(source))
    return applier.seen


def apply_mutation(source: str, target_index: int) -> tuple[str, str, int] | None:
    """Mutated source, its description and line — or None if the index has no site."""
    tree = ast.parse(source)
    applier = _MutationApplier(target_index)
    mutated_tree = applier.visit(tree)
    if applier.applied is None:
        return None
    ast.fix_missing_locations(mutated_tree)
    return (ast.unparse(mutated_tree), applier.applied, applier.applied_line)


def run_tests(working_directory: Path, test_paths: list[str]) -> bool:
    """True when the suite passes. A pass against a mutant means it SURVIVED."""
    completed = subprocess.run(  # noqa: S603
        [
            sys.executable,
            "-m",
            "pytest",
            "-x",
            "-q",
            "--no-header",
            "-p",
            "no:randomly",
            *test_paths,
        ],
        cwd=working_directory,
        capture_output=True,
        timeout=1800,
        check=False,
        env={"PATH": "/usr/bin:/bin", "PYTHONPATH": str(working_directory / "src")},
    )
    return completed.returncode == 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--target", type=Path, required=True, help="file or package to mutate")
    parser.add_argument("--tests", nargs="+", required=True)
    parser.add_argument("--max-mutants", type=int, default=40)
    parser.add_argument("--seed", type=int, default=20260811)
    arguments = parser.parse_args()

    repository_root = Path(__file__).resolve().parent.parent
    target = (repository_root / arguments.target).resolve()
    source_files = sorted(target.rglob("*.py")) if target.is_dir() else [target]
    source_files = [path for path in source_files if path.name != "__init__.py"]

    sites: list[tuple[Path, int]] = []
    for source_file in source_files:
        total = count_mutation_sites(source_file.read_text())
        sites.extend((source_file, index) for index in range(total))
    print(f"{len(sites)} mutation sites across {len(source_files)} files")

    random.seed(arguments.seed)
    random.shuffle(sites)
    chosen = sites[: arguments.max_mutants]

    survivors: list[Mutant] = []
    killed = 0
    for ordinal, (source_file, site_index) in enumerate(chosen, start=1):
        original_source = source_file.read_text()
        mutation = apply_mutation(original_source, site_index)
        if mutation is None:
            continue
        mutated_source, description, line_number = mutation
        if mutated_source == ast.unparse(ast.parse(original_source)):
            continue

        with tempfile.TemporaryDirectory(prefix="mutation-") as scratch:
            scratch_root = Path(scratch) / "repo"
            shutil.copytree(
                repository_root,
                scratch_root,
                ignore=shutil.ignore_patterns(
                    ".git", ".venv", "__pycache__", ".pytest_cache", ".mypy_cache", ".hypothesis"
                ),
            )
            (scratch_root / source_file.relative_to(repository_root)).write_text(mutated_source)
            survived = run_tests(scratch_root, arguments.tests)

        relative = source_file.relative_to(repository_root)
        if survived:
            survivors.append(Mutant(relative, line_number, description))
            print(f"  [{ordinal}/{len(chosen)}] SURVIVED {relative}:{line_number} {description}")
        else:
            killed += 1
            print(f"  [{ordinal}/{len(chosen)}] killed   {relative}:{line_number} {description}")

    attempted = killed + len(survivors)
    print(f"\nmutation score: {killed}/{attempted} killed")
    if survivors:
        print("\nSURVIVORS — each is a missing test or a line that does not matter:")
        for survivor in survivors:
            print(f"  {survivor.file_path}:{survivor.line_number}  {survivor.description}")
    return 1 if survivors else 0


if __name__ == "__main__":
    sys.exit(main())
